Civil Engineer/HCI_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('',include('tower.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_DIR)

Civil Engineer/accounts/urls.py
from django.urls import path
from .views import *

app_name="accounts"
# or  namespace='blog') inside the url to that file


urlpatterns = [
    path("login/",login_view,name="login"),
    path("logout/",logout_view,name="logout"),
]

Civil Engineer/tower/urls.py
from django.urls import path
from .views import *

app_name="tower"
# or  namespace='blog') inside the url to that file


urlpatterns = [
    path('',home,name='home'),

    path('test/add_workers',add_workers,name="test_add_workers"),
    path('test/add_operations',add_operations,name="test_add_operations"),
    path('test/download_operations',download_operations,name="test_download_operations"),
    path('test/download_operations/<int:num>',download_operations,name="test_download_operations"),
    path('test/download_operations/<slug:num>',download_operations,name="test_download_operations"),
    path('test/show_char',show_char,name="test_show_char"),
    path('test',test,name="test"),

    path("engineer/home",engineer_home,name="engineer_home"),
    path('engineer/workers',engineer_workers,name="engineer_workers"),
    path("engineer/foremen",engineer_foremen,name="engineer_foremen"),
    path("engineer/levels",engineer_levels,name="engineer_levels"),
    path("engineer/level/<int:num>",engineer_level,name="engineer_level"),
    path("engineer/level/assign-froeman",assign_foreman,name="assign_foreman"),
    path("engineer/level/remove-foreman/<int:level_num>",remove_foreman,name="remove_foreman"),
    path("engineer/worker/add",add_worker,name="add_worker"),
    path("engineer/worker/edit",edit_worker,name="edit_worker"),
    path("engineer/worker/delete",delete_worker,name="delete_worker"),
    path("engineer/foreman/add",add_foreman,name="add_foreman"),
    path("engineer/foreman/edit",edit_foreman,name="edit_foreman"),
    path("engineer/foreman/delete",delete_foreman,name="delete_foreman"),


    path("operation/delete/<int:id>",delete_operation,name="delete_operation"),
    path("operation/create",create_operation,name="create_operation"),
    path("operation/changeprogress",operation_progress,name="operation_progress"),
    path("operation/changeprogress/worker",operation_progress_worker,name="operation_progress_worker"),



    path("foreman/home",foreman_home,name="foreman_home"),
    path('forman/levels',foreman_levels,name="foreman_levels"),
    path('forman/level/<int:num>',foreman_levels,name="foreman_level"),
    path('forman/workers/<int:type_id>',worker_with_some_type,name="foreman_workers"),
    path('pdf/delete/<int:id>',delete_pdf,name="delete_pdf"),
    path('pdf/create',create_pdf,name="create_pdf"),

    path("worker/home",worker_home,name="worker_home"),

]

Civil Engineer/tower/models.py
from django.db import models
from accounts.models import User
# Create your models here.

worker_choices = {
    ('none','none'),
    ('painting','painting'),
    ('testing pipes','testing'),
    ('fiting pipes','fitting'),
    ('clean rooms','rooms'),
    ('clean stairs','stairs'),
    ('clean bathrooms','bathrooms'),
}

worker_choices = {
('painter','painter'),
('cleaner','cleaner'),
('plumber','plumber'),
}

class Level(models.Model):
    foreman = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True)
    name = models.IntegerField()

    def __str__(self):
        return f'LeveL({self.name})'

    def files(self):
        return Report.objects.filter(level = self)

class Report(models.Model):
    file = models.FileField()
    writer = models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    level = models.ForeignKey(Level,on_delete=models.CASCADE,default=1)

    def get_path(self):
        return "/media/"+str(self.file)



class Operation_type(models.Model):
    name = models.CharField(max_length=30)
    allowed = models.CharField(max_length=30,choices=worker_choices)
    level = models.ForeignKey(Level,on_delete=models.SET_NULL,null=True,blank=True)

    def __str__(self):
        return f"{self.name}"


    def operations(self):
        return Operation.objects.filter(type=self).order_by("deadline")


class Operation(models.Model):
    worker = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True)
    level = models.ForeignKey(Level,on_delete=models.CASCADE)
    type = models.ForeignKey(Operation_type,on_delete=models.CASCADE)
    progress = models.IntegerField(default=0)
    must_finish = models.IntegerField()
    deadline = models.DateField()
    finished = models.DateField(blank=True,null=True)
    description = models.TextField(blank=True,null=True);


    def __str__(self):
        return f'{self.type} : {self.progress}/{self.must_finish}'


    def percent(self):
        return (self.progress*100)//self.must_finish

    def get_description(self):
        if(self.description):
            return self.description
        else:
            return f'{self.type} ({self.progress}/{self.must_finish})'

class Messages(models.Model):
    level = models.ForeignKey(Operation,on_delete = models.CASCADE)
    progress_changing = models.IntegerField()
    content = models.TextField()
    sender = models.ForeignKey(User,related_name="sender",on_delete=models.CASCADE)
    receiver = models.ForeignKey(User,related_name="receiver",on_delete=models.CASCADE)

Civil Engineer/templates/engineer/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/engineer_dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
    <title>{% block title %}{% endblock %}</title>
    {% block style %}

    {% endblock %}
</head>

<body>
    <div class="r_container">
        <div class="r_navbar">
            <header>
              <div class="left_area">
                <h3>Project <span>Name</span></h3>
              </div>
              <input type="search" placeholder="search..">
              <div class="right_area">
                <a href="{% url 'accounts:logout' %}" class="r_logout_btn">Logout</a>
              </div>
            </header>
        </div>
        <div class="r_sidebar">
            <center>
            <img src="{% static 'images/about.jpg' %}" alt="" class="profile_image">
            <h4>Jessica</h4>
            </center>
            <a href="{% url 'tower:engineer_home' %}"><i class="fas fa-desktop"></i><span>Dashboard</span></a>
            <a href="{% url 'tower:engineer_levels' %}" ><i class="fa fa-building"></i><span>Levels</span></a>
            <a href="{% url 'tower:engineer_workers' %}"><i class="fas fa-table"></i><span>Workers</span></a>
            <a href="{% url 'tower:engineer_foremen' %}"><i class="fas fa-table"></i><span>Foremen</span></a>
        </div>
        <div class="r_content">
          <div style="height:1300px">
            {% if messages %}

                {% for message in messages %}
                  <div class="alert alert-danger">
                    {{ message }}
                  </div>
                {% endfor %}
            {% endif %}
            {% block content %}
            {% endblock %}
          </div>
        </div>
    </div>



  <script>
        var dropdown = document.getElementsByClassName("drop");
        var i;

        for (i = 0; i < dropdown.length; i++) {
            dropdown[i].addEventListener("click", function() {
            this.classList.toggle("active");
            var dropdownContent = this.nextElementSibling;
            if (dropdownContent.style.display === "block") {
                dropdownContent.style.display = "none";
            } else {
                dropdownContent.style.display = "block";
            }
    });
}
    </script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <script type="text/javascript">
    function delete_swal(url,message,confirm){
        swal.fire({
          title: 'Are you sure?',
          text: message,
          icon: 'warning',
          showCancelButton: true,
          confirmButtonColor: '#3085d6',
          cancelButtonColor: '#d33',
          confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
          if (result.value) {
            window.location = url;
            Swal.fire(
              'Deleted!',
              confirm,
              'success'
            )
          }
        })

      }
    </script>
    {% block script %}

    {% endblock %}
</body>
</html>

Civil Engineer/templates/engineer/home.html
{% extends 'engineer/base.html' %}
{% load static %}

{% block style %}

    <link type="text/css" rel="stylesheet" href="{% static 'css/stylesheet.css' %}" />


{% endblock %}

{% block content %}




<!-- four squares -->
<div class="row">
  <div class="col-md-3 col-sm-6" >
    <div class="square_card m-3 p-2" >
      <h1 class="text-center">plumbers</h1> <p> {{plumbers}}</p>
    </div>
  </div>
  <div class="col-md-3 col-sm-6" >
    <div class="square_card m-3 p-2" >
      <h1 class="text-center">Clean Workers </h1> <p>  {{cleaners}}</p>
    </div>
  </div>
  <div class="col-md-3 col-sm-6" >
    <div class="square_card m-3 p-2" >
      <h1 class="text-center">Painters</h1> <p> {{painters}}</p>
    </div>
  </div>
  <div class="col-md-3 col-sm-6" >
    <div class="square_card m-3 p-2" >
        <h1 class="text-center">Foremen</h1> <p> {{foremen}}</p>
    </div>
  </div>
</div>



<div class="info">
  <section>

    <div class="chart row m-3">

        <div class="col-12">
          <button  type="button" onclick="setValues()"class="btn btn-warning">Zoom In</button>
          <canvas id="myChart" width="320" height="100"></canvas>
          <h3></h3>
          <h4></h4>
        </div>

    </div>

    <div class="chart row m-3">
        <div class="col-6">
          <div class="">
            <canvas id="myBarChart" width="150" height="100"></canvas>
          </div>
        </div>
        <div class="col-6">
          <div class="">
            <canvas id="myChart2" width="200" height="100"></canvas>
          </div>
        </div>
    </div>
  </section>
</div>


<div class="mt-5 pt-5">

</div>


{% endblock %}

{% block script %}

    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <script type="text/javascript">
      const api_url = 'http://mina381.pythonanywhere.com/test/download_operations'
    </script>
    <script src="{% static 'js/all_charts.js' %}"></script>

{% endblock %}

Civil Engineer/templates/engineer/levels.html
{% extends 'engineer/base.html' %}
{% load static %}

{% block title %} Levels {% endblock %}


{% block style %}
<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
<link rel="stylesheet" href="{% static 'css/engineer_levels.css' %}">

<style media="screen">
  .val{
    color:white;
    font-weight: bold;

  }.more_info{
    color:white;
  }
  .more_info:hover{
    color:#ccc;
  }
  .add{
    color:white;
  }
  .add:hover{
    color:#ccc;
  }
  .remove{
    color:black;
  }

</style>
{% endblock %}


{% block content %}



<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">
                <form id='form' action="{% url 'tower:assign_foreman' %}" method="POST" enctype="multipart/form-data">
                  {% csrf_token %}
                  <input id="level_num" type="hidden" name="level_num">
                  <div class="form-group">

                    <label for="foreman" class="col-form-label">Choose Foreman</label>
                    <select id='foreman' class="form-control" name="foreman">
                      {% for foreman in foremen %}
                        <option value="{{foreman.id}}">{{foreman.full_name}}</option>
                      {% endfor %}
                    </select>
                  </div>

                  <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      <button type="submit" class="btn btn-primary">Submit</button>
                  </div>


                </form>
            </div>


        </div>
    </div>
</div>



<div class="main_cont">
  {% for level in levels %}
  <div class="box">
      <div class="glass"></div>
      <div class="content">
          <h2>Floor Level : {{level.level__name}}</h2><br><br>
          <div class="">
            <strong>Foremen : </strong>
            {% if level.foreman_name %}
              <span class="val"> {{level.foreman_name}}</span>
              <a title="remove" style="color:red;font-size:25px;" class="remove ml-2 fas fa-backspace" href="{% url 'tower:remove_foreman' level.level__name %}">

              </a>
            {% else %}
              <span class="val">
                <a style="width:90px; padding: 8px;" onclick="mod({{level.level__name}})" class="btn btn-primary" data-toggle="modal" data-target="#myModal">+ Add</a>
              </span>
            {% endif %}
          </div>
          <div class="">
            <strong>num of painters : </strong><span class="val"> {{level.painters}}</span>
          </div>
          <div class="">
            <strong>num of plumbers : </strong><span class="val"> {{level.plumbers}}</span>
          </div>
          <div class="">
            <strong>num of clean-workers : </strong><span class="val"> {{level.cleaners}}</span>
          </div>

          <div class="skills">
            <label for="file"><h3>PROGRESS</h3></label>
            <progress id="file" value="{{level.prog}}" max="{{level.fin}}" class="classprog"></progress>
          </div>
          <a  href="{% url 'tower:engineer_level' level.level__name %}" class="btn btn-dark more-info">More Information</a>
      </div>
  </div>
  {% endfor %}

</div>
{% endblock %}



{% block script %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>



<script type="text/javascript">

  function change_location(location){
    window.location = location;
  }
  //
  //
  // for(let i=0;i<rem.length;i++){
  //   rem[i].addEventListener('click',function(){
  //     event.preventDefault();
  //     swal({
  //       text:"Are you sure you want to delete it ?",
  //       buttons:true
  //     }).then((value)=>
  //         {
  //           if(value)
  //           {
  //               window.location = this.href;
  //           }
  //         })
  //   })
  // }


  function mod(num){
    document.getElementById('level_num').value = num;
  }

  rem = document.querySelectorAll('.remove');
  for(let i=0;i<rem.length;i++){
    rem[i].addEventListener('click',function(){
      event.preventDefault();
      url = this.href
      console.log(url);
      swal.fire({
        title: 'Are you sure?',
        text: "you want to remove the foreman from this floor",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Yes, remove him!'
      }).then((result) => {
        if (result.value) {
          window.location = url;
          Swal.fire(
            'Removed!',
            confirm,
            'success'
          )
        }
      })


})
}




</script>

{% endblock %}

Civil Engineer/templates/engineer/workers.html
{% extends 'engineer/base.html' %}
{% load static %}



{% block title %} Workers {% endblock %}

{% block style %}

<!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
<!-- Google Fonts Roboto -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
<!-- Data Table -->
<link href="{% static 'css/datatables.min.css' %}" rel="stylesheet">

<style>
  input[type=checkbox]{
    margin: 10px;
    cursor: pointer;
-moz-transform: scale(1.4); /* FF */
  }
  body{
    color:white;
  }

</style>
{% endblock %}


{% block content %}









  <div class="wrapper-editor">

    <div class="block my-4">
      <div class="d-flex justify-content-center">
        <p class="h5 text-primary createShowP">Workers</p>
      </div>
    </div>

    <div class="row d-flex justify-content-center modalWrapper">
      <div class="modal fade addNewInputs" id="modalAdd" tabindex="-1" role="dialog" aria-labelledby="modalAdd"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header text-center">
              <h4 class="modal-title w-100 font-weight-bold text-primary ml-5">Add new Worker</h4>
              <button type="button" class="close text-primary" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <form class="" action="{% url 'tower:add_worker' %}" method="POST">
            <div class="modal-body mx-3">



                {% csrf_token %}
                <div class="md-form mb-5">
                  <input required name="first_name" autocomplete="false" type="text" id="addName" class="form-control validate">
                  <label data-error="wrong" data-success="right" for="firstName">First Name</label>
                </div>

                <div class="md-form mb-5">
                  <input required name="last_name" autocomplete="false" type="text" id="addName" class="form-control validate">
                  <label data-error="wrong" data-success="right" for="lastName">Last Name</label>
                </div>

                <div class="md-form mb-5">
                  <input required name="email" readonly onfocus="this.removeAttribute('readonly');" autocomplete="off" type="email" id="addEmail" class="form-control validate">
                  <label data-error="wrong" data-success="right" for="inputOfficeInput">Email</label>
                </div>

                <div class="md-form mb-5">
                  <input required name="password" type="password" id="addpassword" class="form-control validate">
                  <label data-error="wrong" data-success="right" for="inputOfficeInput">Password</label>
                </div>

                <div class="md-form mb-5">
                  <select required name="type" class="browser-default custom-select custom-select-lg mb-3">
                    <option value="" disabled selected>Choose Job</option>
                    <option value="painter">Painter</option>
                    <option value="plumber">Plumber</option>
                    <option value="cleaner">Clean worker</option>
                  </select>
                </div>



            </div>
            <div class="modal-footer d-flex justify-content-center buttonAddFormWrapper">
              <button type='submit' class="btn btn-outline-primary btn-block buttonAdd">Add Worker
                <i class="fas fa-paper-plane-o ml-1"></i>
              </button>
            </div>
            </form>
          </div>
        </div>
      </div>

      <div class="text-center">
        <a href="" class="btn add btn-info btn-rounded btn-sm" data-toggle="modal" data-target="#modalAdd">Add<i
            class="fas fa-plus-square ml-1"></i></a>
      </div>

      <!-- <div class="modal fade modalEditClass" id="modalEdit" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header text-center">
              <h4 class="modal-title w-100 font-weight-bold text-secondary ml-5">Edit Worker</h4>
              <button type="button" class="close text-secondary" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body mx-3">


              <form class="" action="index.html" method="post">

                <div class="form-group mb-5">
                  <label data-error="wrong" data-success="right" for="inputName">Name</label>
                  <input type="text" id="editName" class="form-control validate">
                </div>

                <div class="form-group mb-5">
                  <label data-error="wrong" data-success="right" for="inputPosition">Job</label>
                  <input type="text" id="editJob" class="form-control validate">
                </div>


                <div class="form-group mb-5">
                  <label data-error="wrong" data-success="right" for="inputOfficeInput">Email</label>
                  <input type="text" id="editEmail" class="form-control validate">
                </div>
              </form>


            </div>
            <div class="modal-footer d-flex justify-content-center editInsideWrapper">
              <button class="btn btn-outline-secondary btn-block editInside" data-dismiss="modal">Edit
                worker
                <i class="fas fa-paper-plane-o ml-1"></i>
              </button>
            </div>
          </div>
        </div>
      </div> -->


      <div class="modal fade" id="modalDelete" tabindex="-1" role="dialog" aria-labelledby="modalDelete"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header text-center">
              <h4 class="modal-title w-100 font-weight-bold ml-5 text-danger">Delete</h4>
              <button type="button" class="close text-danger" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body mx-3">
              <p style="color:black;" class="text-center h4">Are you sure to delete selected row?</p>

            </div>
            <div class="modal-footer d-flex justify-content-center deleteButtonsWrapper">
              <button type="button" class="btn btn-danger btnYesClass" id="btnYes" data-dismiss="modal">Yes</button>
              <button type="button" class="btn btn-primary btnNoClass" id="btnNo" data-dismiss="modal">No</button>
            </div>
          </div>
        </div>
      </div>

      <div class="text-center">
        <button type='button' id='delete_button' class="btn btn-danger btn-sm btn-rounded buttonDelete" data-toggle="modal" data-target="#modalDelete"
          disabled>Delete<i class="fas fa-times ml-1"></i></a>
      </div>
    </div>


<div class="container">

<form action="{% url 'tower:delete_worker' %}" method="POST" id='form'>
{% csrf_token %}
<table id="table" style="background: #262B49" class="table table-bordered table-sm table-dark" cellspacing="0" width="100%">
  <thead>
    <tr>

      <th class="th-sm">Name</th>
      <th class="th-sm">Job</th>
      <th class="th-sm">Operations</th>
      <th class="th-sm">Email</th>
      <th class="th-sm"><span id='counter'>0</span> row selected</th>

    </tr>
  </thead>
  <tbody>
    {% for worker in workers %}
    <tr>
        <td>{{worker.first_name}} {{worker.last_name}}</td>
        <td>{{worker.type}}</td>
        <td>{{worker.operation_set.count}}</td>
        <td>{{worker.email}}</td>
        <!-- <td>
          <button type="button" class="btn edit btn-info btn-rounded btn-sm buttonEdit" data-toggle="modal" data-target="#modalEdit"
            >Edit<i class="fas fa-pencil-square-o ml-1"></i></a>
        </td> -->
        <td>
          <input class="checkbox-button" type="checkbox" name="id[]" value="{{worker.id}}">
        </td>
    </tr>
    {% endfor %}
  </tbody>
  <tfoot>
    <tr>

      <th class="th-sm">Name</th>
      <th class="th-sm">Job</th>
      <th class="th-sm">Operations</th>
      <th class="th-sm">Email</th>
      <th class="th-sm"></th>
    </tr>
  </tfoot>
</table>

    </tr>
  </tfoot>
</table>

</div>





</form>



{% endblock %}



{% block script %}


<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>

<script type="text/javascript" src="{% static 'js/datatables.min.js' %}"></script>


<script >
  let counter = 0;
  $('#table').DataTable({
    columnDefs: [{orderable: false,targets: 4}]
  });
  $('.dataTables_length').addClass('bs-select');

  $(document).ready(function () {
  $('.checkbox-button').click(function(){
      console.log("clicked");
      if($(this).prop("checked") == true){
          counter+=1;
          $('#delete_button').attr('disabled',false);
      }
      else if($(this).prop("checked") == false){
          counter-=1;
          counter = Math.max(counter,0);
          if(counter===0){
            $('#delete_button').attr('disabled',true);
          }

      }
      $('#counter').text(counter);

  });

  $('#btnYes').click(function(){
    $('#form').submit();
  });

  // $('.edit').click(function(){
  //   let siblings = $(this).parent().siblings()
  //   let first_name = siblings[0].innerText.split(" ")[0];
  //   let last_name =  siblings[0].innerText.split(" ")[1];
  //   let email  = siblings[3].innerText;
  //   console.log(name,job,email)
  //   $('#editfirstName').val(name)
  //   $('#editLastName').val(job)
  //   $('#editEmail').val(email)
  // });


  });



</script>
{% endblock %}