Civil Engineer/HCI_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('',include('tower.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_DIR)

Civil Engineer/accounts/urls.py
from django.urls import path
from .views import *

app_name="accounts"
# or  namespace='blog') inside the url to that file


urlpatterns = [
    path("login/",login_view,name="login"),
    path("logout/",logout_view,name="logout"),
]

Civil Engineer/tower/urls.py
from django.urls import path
from .views import *

app_name="tower"
# or  namespace='blog') inside the url to that file


urlpatterns = [
    path('',home,name='home'),

    path('test/add_workers',add_workers,name="test_add_workers"),
    path('test/add_operations',add_operations,name="test_add_operations"),
    path('test/download_operations',download_operations,name="test_download_operations"),
    path('test/download_operations/<int:num>',download_operations,name="test_download_operations"),
    path('test/download_operations/<slug:num>',download_operations,name="test_download_operations"),
    path('test/show_char',show_char,name="test_show_char"),
    path('test',test,name="test"),

    path("engineer/home",engineer_home,name="engineer_home"),
    path('engineer/workers',engineer_workers,name="engineer_workers"),
    path("engineer/foremen",engineer_foremen,name="engineer_foremen"),
    path("engineer/levels",engineer_levels,name="engineer_levels"),
    path("engineer/level/<int:num>",engineer_level,name="engineer_level"),
    path("engineer/level/assign-froeman",assign_foreman,name="assign_foreman"),
    path("engineer/level/remove-foreman/<int:level_num>",remove_foreman,name="remove_foreman"),
    path("engineer/worker/add",add_worker,name="add_worker"),
    path("engineer/worker/edit",edit_worker,name="edit_worker"),
    path("engineer/worker/delete",delete_worker,name="delete_worker"),
    path("engineer/foreman/add",add_foreman,name="add_foreman"),
    path("engineer/foreman/edit",edit_foreman,name="edit_foreman"),
    path("engineer/foreman/delete",delete_foreman,name="delete_foreman"),


    path("operation/delete/<int:id>",delete_operation,name="delete_operation"),
    path("operation/create",create_operation,name="create_operation"),
    path("operation/changeprogress",operation_progress,name="operation_progress"),
    path("operation/changeprogress/worker",operation_progress_worker,name="operation_progress_worker"),



    path("foreman/home",foreman_home,name="foreman_home"),
    path('forman/levels',foreman_levels,name="foreman_levels"),
    path('forman/level/<int:num>',foreman_levels,name="foreman_level"),
    path('forman/workers/<int:type_id>',worker_with_some_type,name="foreman_workers"),
    path('pdf/delete/<int:id>',delete_pdf,name="delete_pdf"),
    path('pdf/create',create_pdf,name="create_pdf"),

    path("worker/home",worker_home,name="worker_home"),

]

Civil Engineer/templates/foreman/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/engineer_dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
    <title>{% block title %}{% endblock %}</title>
    {% block style %}

    {% endblock %}
</head>

<body>
    <div class="r_container">
        <div class="r_navbar">
            <header>
              <div class="left_area">
                <h3>Project <span>Name</span></h3>
              </div>
              <input type="search" placeholder="search..">
              <div class="right_area">

                <a href="{% url 'accounts:logout' %}" class="r_logout_btn">Logout</a>
              </div>
            </header>
        </div>
        <div class="r_sidebar">
            <center>
            <img src="{% static 'images/about.jpg' %}" alt="" class="profile_image">
            <h4>{{user.full_name}}</h4>
            </center>
            <a href="{% url 'tower:foreman_home' %}"><i class="fas fa-desktop"></i><span>Dashboard</span></a>
            {% if levels %}
              <a href="javascript:;" class="drop"><i class="fa fa-building"></i>
              <span>Levels</span>
                 <i class="fa fa-caret-down"></i>
                  <div class="dropdown-container">

                      {% for level in levels %}
                        <a href="{% url 'tower:foreman_level' level.name %}"><i class="fa fa-info"></i>Level {{level.name}}</a>
                      {% endfor %}

                  </div>
              </a>

            {% endif %}
        </div>
        <div class="r_content">
          <div style="height:1300px">
            {% if messages %}

                {% for message in messages %}
                  <div class="alert alert-danger">
                    {{ message }}
                  </div>
                {% endfor %}
            {% endif %}
            {% block content %}
            {% endblock %}
          </div>
        </div>
    </div>



  <script>
        var dropdown = document.getElementsByClassName("drop");
        var i;

        for (i = 0; i < dropdown.length; i++) {
            dropdown[i].addEventListener("click", function() {
            this.classList.toggle("active");
            var dropdownContent = this.nextElementSibling;
            if (dropdownContent.style.display === "block") {
                dropdownContent.style.display = "none";
            } else {
                dropdownContent.style.display = "block";
            }
    });
}
    </script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <script src="{% static 'js/sending_data.js' %}"></script>
    <script type="text/javascript">
    function delete_swal(url,message,confirm){
        swal.fire({
          title: 'Are you sure?',
          text: message,
          icon: 'warning',
          showCancelButton: true,
          confirmButtonColor: '#3085d6',
          cancelButtonColor: '#d33',
          confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
          if (result.value) {
            window.location = url;
            Swal.fire(
              'Deleted!',
              confirm,
              'success'
            )
          }
        })

      }
    </script>
    {% block script %}

    {% endblock %}
</body>
</html>

Civil Engineer/templates/foreman/home.html
{% extends 'foreman/base.html' %}
{% load static %}

{% block style %}

    <link type="text/css" rel="stylesheet" href="{% static 'css/stylesheet.css' %}" />


{% endblock %}

{% block content %}


<div class="info">
  <section>

    <div class="chart row m-3">

        <div class="col-12">
          <button  type="button" onclick="setValues()"class="btn btn-warning">Zoom In</button>
          <canvas id="myChart" width="320" height="100"></canvas>
          <h3></h3>
          <h4></h4>
        </div>

    </div>

    <div class="chart row m-3">
        <div class="col-6">
          <div class="">
            <canvas id="myBarChart" width="150" height="100"></canvas>
          </div>
        </div>
        <div class="col-6">
          <div class="">
            <canvas id="myChart2" width="200" height="100"></canvas>
          </div>
        </div>
    </div>
  </section>
</div>


<div class="mt-5 pt-5">

</div>


{% endblock %}

{% block script %}

    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <script type="text/javascript">
      const api_url = 'http://mina381.pythonanywhere.com/test/download_operations/{{user.id}}'
    </script>
    <script src="{% static 'js/all_charts.js' %}"></script>

{% endblock %}

Civil Engineer/templates/foreman/level.html
{% extends 'foreman/base.html' %}
{% load static %}


{% block title %}
Level {{level_num}}
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/progress.css' %} ">
<style media="screen">
  .modal-dialog{
      width:85%;
  }.embed_par{
    height:750px;
  }
</style>
{% endblock %}


{% block content %}




<div class="modal fade" id="view_pdf_modal" role="dialog">
  <div class="modal-dialog">
        <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h1 >Open in Browser <a  class="embed_link" target="_blank" href="#"> Click Here</a></h1>
      </div>
      <div class="modal-body">
        <div class="embed_par">
          <embed id='embed' src="#" frameborder="0" width="100%" height="100%">
        </div>
      </div>
    </div>
  </div>
</div>



<div class="modal fade" id="send_pdf" role="dialog">
  <div class="modal-dialog">
        <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <form action="{% url 'tower:create_pdf' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="modal-body">


            <div class="form-group">
              <label for="recipient-name" class="col-form-label">Title:</label>
              <input required type="text" class="form-control" name="title" value="">
            </div>

            <div class="form-group">
              <label for="recipient-name" class="col-form-label">File:</label>
              <input required type="file" class="form-control-file" name="file" value="">
            </div>


            <input type="hidden" name="level" value="{{ level_num }}">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Upload file</button>
        </div>
      </form>
    </div>
  </div>
</div>



<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New message</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="{% url 'tower:create_operation' %}" method="POST" >
        {% csrf_token %}

        <div class="modal-body">
            <div class="form-group">
              <label for="recipient-name" class="col-form-label">type:</label>
              <select id="select_type" onchange="get_workers()" class="custom-select" name="type">
                <option required disabled selected value="">Choose type</option>
                {% for op_type in operation_types %}
                  <option value="{{op_type.id}}">{{op_type.name}}</option>
                {% endfor %}
              </select>
            </div>

            <div class="form-group">
              <label for="message-text" class="col-form-label">description:</label>
              <textarea name="description" class="form-control" id="message-text"></textarea>
            </div>

            <div class="form-group">
              <label for="message-text" class="col-form-label">DeadLine:</label>
              <input required name="deadline" class="form-control" type="date" id="message-text">
            </div>

            <div class="form-group">
              <label for="message-text" class="col-form-label">amount to finish :</label>
              <input required type="number" name="must_finish" class="form-control" id="message-text">
            </div>

            <div class="form-group">
              <label for="message-text" class="col-form-label">Worker:</label>
              <select required class="custom-select" id="select_worker" name="worker">

              </select>
            </div>

            <input type="hidden" name="level" value="{{ level_num }}">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Send message</button>
        </div>
      </form>
    </div>
  </div>
</div>

<div class="modal fade" id="change_progress_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="change_progress_modal">New message</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="{% url 'tower:operation_progress' %}" method="POST" >
        {% csrf_token %}

        <div class="modal-body">

          <div class="form-group">
            <label for="message-text" class="col-form-label">New Progress :</label>
            <input required type="number" name="progress" class="form-control" id="message-text">
          </div>

            <input type="hidden" id="operation_id" name="operation_id" value="">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Send message</button>
        </div>
      </form>
    </div>
  </div>
</div>



<div>
  <!-- start progress part  -->
  <div class="progress_part">
    <h1 class="align-left"> Level {{level_num}}</h1>
    <button type="button" class="float-right mr-5 btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">+ Add Operation</button>
    <br><br>
    <div class="accordion" id="accordionExample">
      {% for operation_type in operation_types %}
      <div class="card">
        <div class="card-header" id="head_{{operation_type.id}}">
          <h2 class="mb-0">
            <button class="button_style cblack btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#id_{{operation_type.id}}" aria-expanded="true" aria-controls="id_{{operation_type.id}}">
            {{operation_type.name}}

            </button>
          </h2>
        </div>
        <!--begin of data-->
        <div id="id_{{operation_type.id}}" class="collapse {% if forloop.counter == 1 %}show{% endif %}" aria-labelledby="head_{{operation_type.id}}" data-parent="#accordionExample">
          <div class="card-body">
            <!--begin of data-->
            <ul class="list-group list-group-flush">
              {% for operation in operation_type.operations %}
                <li id='op_{{operation.id}}' class="list-group-item pb-4 pt-4">

                  <p class="pb-3">
                    <span class="float-left">{{operation.worker}}</span>
                    <span class="float-right">
                      <button onclick="change_progress({{operation.id}})" class='btn btn-primary'  data-toggle="modal" data-target="#change_progress_modal" data-whatever="@getbootstrap" type="button" name="button">Change Progress</button>
                      <button onclick="delete_progress({{operation.id}})" class="btn btn-danger">Delete</button>
                    </span>
                  </p><br>
                  <p>
                    <span class="float-left">Task : {{operation.get_description}}</span>
                    <span class="float-right">Deadline : {{operation.deadline}} </span>
                  </p><br>

                  <div class="progress">
                    <div class="progress-bar" role="progressbar" style='width: {{operation.percent}}%;' aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">({{operation.percent}})% </div>
                   </div>
                </li>
              {% endfor %}

            </ul>
              <!--end of part of data-->
          </div>
        </div>
      </div>
      {% endfor %}
        <!--card2-->

    </div>
  </div>

  <!-- end progress part  -->
  <!-- start report part  -->
  <div class="reports">
      <div class="content_side">
        {% for file in current_level.files %}
          <div class="pdf">
            <div class="iconpdf">
              <!-- <a onclick='open_pdf()' href="{{ file.get_path }}" target="_blank" data-toggle="modal" data-target="#view_pdf_modal">  <i class="far fa-file-pdf"> PDF1</i></a> -->
              <a href="{{ file.get_path }}" target="_blank" >  <i class="far fa-file-pdf"> {{file.title}}</i></a>
            </div>
            <div class="my_close">
              <a id="deleteId_{{file.id}}" href="{% url 'tower:delete_pdf' 123456 %}"  style="color:red" class="fas fa-window-close"></a>
            </div>
          </div>
        {% endfor %}


      </div>
      <!-- part of (add button)  -->
    <div class="button_side">
     <button style="background-color: #252C48;" class="button_style" type="button" name="button" data-toggle="modal" data-target="#send_pdf"> Add reprot</button>
    </div>
  </div>

</div>
{% endblock %}


{% block script %}

<script src="http://kit.fontawesome.com/a076d05399.js"></script>

<script>
//
// var close = document.querySelectorAll(".close");
//
// for(var i=0;i<close.length;i++){
// close[i].addEventListener('click', function(){
//   swal({
//     text:"Are you sure you want to delete it ?",
//     buttons:true
//   }).then((value)=>
//       {
//         if(value)
//         {
//             this.parentNode.style.display = 'none';
//         }
//       })
//
// });
// }


close = document.querySelectorAll('.my_close');
for(let i=0;i<close.length;i++){
  close[i].addEventListener('click',function(){
    event.preventDefault();
    url = this.childNodes[1].href
    cur_id = this.childNodes[1].id.split("_")[1]
    url = url.replace('123456',cur_id)
    console.log(url);
    swal.fire({
      title: 'Are you sure?',
      text: "The File be Deleted permanently",
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Yes, Delete it!'
    }).then((result) => {
      if (result.value) {

        getData(url)
        .then(data => {

          Swal.fire(
            'Deleted!',
            data['messaage'],
            'success'
          )
          this.parentNode.style.display = 'none';
        }).catch(function(data) {
          Swal.fire(
            'Failed!',
            data['messaage'],
            'error'
          )
        });;
      }
    })


})
}
// Example POST method implementation:


async function get_workers(){
  val = document.getElementById('select_type').value;
  workers = document.getElementById('select_worker');
  workers.innerHTML = ""
  url = "{% url 'tower:foreman_workers' 123456 %}".replace("123456",val);
  getData(url)
  .then(data => {
    for(let i =0;i<data.length;i++){

      var opt = document.createElement('option');

      // create text node to add to option element (opt)
      opt.appendChild( document.createTextNode(data[i].first_name + " " + data[i].last_name) );

      // set value property of opt
      opt.value = data[i].id;

      // add opt to end of select box (sel)
      workers.appendChild(opt);
    }
  });

}


function change_progress(id){
  document.getElementById('operation_id').value = id;
  console.log(id);
}

function delete_progress(id){
    url = "{% url 'tower:delete_operation' 123456 %}".replace("123456",id);
    console.log(event.target);
    swal.fire({
      title: 'Are you sure',
      text: "you want to delete this operation?",
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Yes, delete it!'
    }).then((result) => {
      if (result.value) {

        getData(url)
        .then(data => {

          Swal.fire(
            'Deleted!',
            data['messaage'],
            'success'
          )
          document.getElementById('op_'+id).style.display = 'none'
        });


      }
    })

  }


  function open_pdf(){
    let e = event.target.parentNode.href;

    console.log(event.target)
    console.log(event.target.parentNode)
    console.log(e);
    document.getElementById('embed').src = e;
    document.getElementById('embed_link').href = e;
  }


</script>

{% endblock %}